import { Platform, StyleSheet } from 'react-native';

import {
  APP_CONTENT_MAX_WIDTH,
  APP_WIDE_CONTENT_MAX_WIDTH,
  wideContentFill,
} from '@/constants/responsiveLayout';
import type { AppTheme } from '@/constants/theme';
import { webFlexFill, webScrollViewportStyle } from '@/constants/webLayout';
import {
  getSegmentTabBarStyles,
  SCREEN_LIST_CONTENT_PADDING_TOP,
  SCREEN_LIST_HEADER_PADDING_BOTTOM,
  SCREEN_LIST_HEADER_PADDING_TOP,
} from '@/constants/segmentTabBar';
import { getScreenFixedHeaderStyles } from '@/constants/screenFixedHeader';
import {
  FEED_ARTICLE_TITLE_PX,
  FEED_BODY_PX,
  FEED_META_TIME_PX,
  FEED_PREVIEW_BODY_PX,
  FEED_SUMMARY_PX,
} from '@/constants/feedTypography';
import type { FeedContentTypography } from '@/services/feedContentWeightPreference';

export function makeNewsStyles(
  theme: AppTheme,
  sf: (n: number) => number,
  ft: FeedContentTypography,
) {
  const segmentTab = getSegmentTabBarStyles(theme, sf);
  const fixedHeader = getScreenFixedHeaderStyles(theme);
  return StyleSheet.create({
    safe: {
      ...webFlexFill,
      backgroundColor: theme.bg,
    },
    mainColumn: {
      ...webFlexFill,
      width: '100%',
      maxWidth: APP_CONTENT_MAX_WIDTH,
      alignSelf: 'center',
    },
    mainColumnWide: {
      ...wideContentFill,
    },
    topFixed: fixedHeader.strip,
    topFixedWide: fixedHeader.stripWide,
    list: {
      ...webScrollViewportStyle,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: SCREEN_LIST_CONTENT_PADDING_TOP,
    },
    adBetweenGroups: {
      marginVertical: 16,
    },
    listHeader: {
      paddingTop: SCREEN_LIST_HEADER_PADDING_TOP,
      paddingBottom: SCREEN_LIST_HEADER_PADDING_BOTTOM,
    },
    listColumn: {
      ...webFlexFill,
      minHeight: 0,
    },
    listColumnDigestStrip: {
      flexShrink: 0,
      paddingHorizontal: 0,
    },
    skeletonBlock: {
      marginTop: 4,
    },
    tagFilterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 20,
      marginBottom: 14,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    tagFilterText: {
      flex: 1,
      minWidth: 0,
      fontSize: ft.ff(FEED_BODY_PX),
      fontWeight: ft.emphasisWeight,
      color: theme.text,
    },
    tagFilterClear: {
      fontSize: ft.ff(FEED_BODY_PX),
      fontWeight: ft.emphasisWeight,
      color: theme.green,
    },
    titleListToggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-end',
      gap: 6,
      marginBottom: 10,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: theme.bgElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.border,
    },
    titleListToggleRowActive: {
      backgroundColor: theme.greenDim,
      borderColor: theme.greenBorder,
    },
    titleListToggleRowPressed: {
      opacity: 0.86,
    },
    titleListToggleText: {
      fontSize: ft.ff(FEED_SUMMARY_PX),
      lineHeight: sf(15),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    titleListToggleTextActive: {
      color: theme.green,
    },
    videoOpenAll: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      marginBottom: 14,
      paddingVertical: 10,
      paddingHorizontal: 11,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
    },
    videoOpenAllPressed: {
      opacity: 0.9,
    },
    videoOpenAllIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    videoOpenAllTitle: {
      flex: 1,
      minWidth: 0,
      fontSize: ft.ff(FEED_PREVIEW_BODY_PX),
      lineHeight: sf(18),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    digestCard: {
      marginBottom: 8,
      paddingHorizontal: 13,
      paddingVertical: 11,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.card,
      gap: 7,
      shadowColor: '#000000',
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 5 },
      elevation: 1,
    },
    digestCardPressed: {
      opacity: 0.88,
    },
    digestTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 16,
    },
    digestKicker: {
      minHeight: 22,
      paddingHorizontal: 8,
      borderRadius: 999,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    digestKickerText: {
      fontSize: ft.ff(FEED_SUMMARY_PX),
      lineHeight: sf(15),
      fontWeight: ft.titleWeight,
      color: theme.green,
    },
    digestHeaderMeta: {
      flexShrink: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    digestCount: {
      flexShrink: 0,
      fontSize: ft.ff(FEED_SUMMARY_PX),
      lineHeight: sf(15),
      fontWeight: ft.emphasisWeight,
      color: theme.textDim,
    },
    digestTitle: {
      fontSize: ft.ff(FEED_ARTICLE_TITLE_PX),
      lineHeight: sf(21),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    digestSummary: {
      fontSize: ft.ff(FEED_BODY_PX),
      lineHeight: sf(18),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    digestChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    digestSymbolChip: {
      overflow: 'hidden',
      minHeight: 24,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      fontSize: ft.ff(FEED_SUMMARY_PX),
      lineHeight: sf(16),
      fontWeight: ft.titleWeight,
      color: theme.green,
    },
    digestSourceChip: {
      overflow: 'hidden',
      maxWidth: 120,
      minHeight: 24,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: theme.bgElevated,
      borderWidth: 1,
      borderColor: theme.border,
      fontSize: ft.ff(FEED_SUMMARY_PX),
      lineHeight: sf(16),
      fontWeight: ft.emphasisWeight,
      color: theme.textMuted,
    },
    digestMoreList: {
      overflow: 'hidden',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
    },
    digestMoreRow: {
      paddingHorizontal: 11,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
      gap: 2,
    },
    digestMoreTitle: {
      fontSize: ft.ff(FEED_PREVIEW_BODY_PX),
      lineHeight: sf(18),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    digestMoreMeta: {
      fontSize: ft.ff(FEED_SUMMARY_PX),
      lineHeight: sf(16),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    digestToggle: {
      alignSelf: 'flex-start',
      minHeight: 30,
      paddingHorizontal: 10,
      borderRadius: 999,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.greenDim,
    },
    digestTogglePressed: {
      opacity: 0.82,
    },
    digestToggleText: {
      fontSize: ft.ff(FEED_BODY_PX),
      lineHeight: sf(17),
      fontWeight: ft.titleWeight,
      color: theme.green,
    },
    watchFilterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      marginBottom: 14,
    },
    watchFilterChip: {
      minHeight: 32,
      paddingHorizontal: 11,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    watchFilterChipActive: {
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
    },
    watchFilterText: {
      fontSize: ft.ff(FEED_BODY_PX),
      lineHeight: sf(17),
      fontWeight: ft.emphasisWeight,
      color: theme.textDim,
    },
    watchFilterTextActive: {
      color: theme.green,
    },
    footerLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
      paddingVertical: 16,
    },
    footerLoadingText: {
      fontSize: ft.ff(FEED_BODY_PX),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    footerLoadMoreButton: {
      minHeight: 38,
      paddingHorizontal: 18,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.green,
    },
    footerLoadMoreText: {
      fontSize: ft.ff(FEED_PREVIEW_BODY_PX),
      fontWeight: ft.titleWeight,
      color: theme.bg,
    },
    segment: segmentTab.segment,
    segBtn: segmentTab.segBtn,
    segBtnVideo: segmentTab.segBtnVideo,
    segmentDivider: segmentTab.segmentDivider,
    segBtnActive: segmentTab.segBtnActive,
    segText: segmentTab.segText,
    segTextActive: segmentTab.segTextActive,
    errBox: {
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.dangerDim,
      borderWidth: 1,
      borderColor: '#FFD6DA',
      marginBottom: 16,
    },
    errText: {
      fontSize: ft.ff(FEED_BODY_PX),
      color: theme.danger,
      lineHeight: sf(18),
      fontWeight: ft.bodyWeight,
    },
    empty: {
      fontSize: ft.ff(FEED_PREVIEW_BODY_PX),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
      marginTop: 8,
    },
  });
}
