import { config } from '../config.mjs';
import { ensureMarketListsShape } from '../marketLists.mjs';
import { DEFAULT_YOUTUBE_CURATION_HANDLES } from '../youtubeCuration.mjs';
import { nowIso } from './time.mjs';

export function defaultUiModelPresets() {
  return {
    openai: ['gpt-4o-mini'],
    claude: ['claude-3-5-haiku-latest'],
    mock: ['mock-news-v1'],
    updatedAt: nowIso(),
  };
}

export function defaultPollingJobs() {
  return [
    {
      jobKey: 'market_news_global',
      displayName: '글로벌 뉴스 최신 수집',
      description: 'Finnhub 글로벌 시장 뉴스 최신 목록을 가져옵니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 1800,
      params: { category: 'general' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_crypto',
      displayName: '크립토 뉴스 최신 수집',
      description: 'Finnhub 크립토 뉴스 최신 목록을 가져옵니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 1800,
      params: { category: 'crypto' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_global_reconcile',
      displayName: '글로벌 뉴스 보정 수집',
      description: 'Finnhub 글로벌 시장 뉴스를 다시 조회해 수정된 제목/요약/소스 정보를 반영합니다.',
      domain: 'news',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 3600,
      params: { category: 'general' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_crypto_reconcile',
      displayName: '크립토 뉴스 보정 수집',
      description: 'Finnhub 크립토 뉴스를 다시 조회해 수정된 제목/요약/소스 정보를 반영합니다.',
      domain: 'news',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 3600,
      params: { category: 'crypto' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_financial_juice',
      displayName: 'Financial Juice (RSS)',
      description: 'Financial Juice 공개 RSS(지연 헤드라인)를 수집해 뉴스 DB에 저장합니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'rss',
      handler: 'financial_juice',
      enabled: false,
      intervalSeconds: 300,
      params: { rssSourceId: 'financial_juice', limit: 40 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_financial_juice_reconcile',
      displayName: 'Financial Juice (RSS) 보정',
      description: 'RSS 항목을 다시 읽어 제목·요약·링크 변경을 반영합니다.',
      domain: 'news',
      operation: 'reconcile',
      provider: 'rss',
      handler: 'financial_juice',
      enabled: false,
      intervalSeconds: 3600,
      params: { rssSourceId: 'financial_juice', limit: 60 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_sec_edgar_filings',
      displayName: 'SEC EDGAR 공시 수집',
      description: '관심종목의 SEC 주요 공시(8-K, 10-Q, 10-K 등)를 뉴스 촉매로 저장합니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'sec',
      handler: 'company_filings',
      enabled: false,
      intervalSeconds: 3600,
      params: {
        listKey: 'default_watchlist',
        forms: ['8-K', '10-Q', '10-K', 'S-1', '6-K', '20-F'],
        daysBack: 14,
        limitPerSymbol: 5,
        requestDelayMs: 150,
      },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_globenewswire_earnings',
      displayName: '뉴스와이어 실적 RSS',
      description: '등록된 실적/운영결과 RSS를 수집해 공식 보도자료 기반 뉴스로 저장합니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'rss',
      handler: 'newswire_rss',
      enabled: false,
      intervalSeconds: 1800,
      params: {
        rssSourceId: 'globenewswire_earnings',
        rssSourceIds: ['globenewswire_earnings', 'prnewswire_earnings'],
        limit: 40,
        daysBack: 7,
        includeKeywords: ['earnings', 'results', 'revenue', 'guidance', 'quarter'],
      },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_economic',
      displayName: '경제지표 최신 수집',
      description: '오늘 이후 경제지표 일정을 가져옵니다.',
      domain: 'calendar',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'economic_calendar',
      enabled: false,
      intervalSeconds: 1800,
      params: { daysBack: 1, daysAhead: 14 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_earnings',
      displayName: '실적 캘린더 최신 수집',
      description: '오늘 이후 실적 발표 일정을 가져옵니다.',
      domain: 'calendar',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'earnings_calendar',
      enabled: false,
      intervalSeconds: 21600,
      params: { daysBack: 3, daysAhead: 30 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'concall_transcripts_recent',
      displayName: '컨콜 트랜스크립트 최신 수집',
      description: '최근 실적 캘린더의 컨콜 트랜스크립트를 API Ninjas에서 가져옵니다.',
      domain: 'concalls',
      operation: 'latest',
      provider: 'ninjas',
      handler: 'earning_transcripts',
      enabled: false,
      intervalSeconds: 21600,
      params: { daysBack: 45, daysAhead: 2, limit: 25, listKey: 'mcap_universe', fallbackLatest: true },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'youtube_economy_latest',
      displayName: '경제 유튜브 최신 수집',
      description: '설정된 경제/시장 채널의 최신 영상을 가져옵니다.',
      domain: 'youtube',
      operation: 'latest',
      provider: 'youtube',
      handler: 'youtube_economy',
      enabled: false,
      intervalSeconds: 1800,
      params: { order: 'date' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'youtube_economy_popular',
      displayName: '경제 유튜브 인기 수집',
      description: '설정된 경제/시장 채널의 인기 영상을 조회수 기준으로 가져옵니다.',
      domain: 'youtube',
      operation: 'popular',
      provider: 'youtube',
      handler: 'youtube_economy',
      enabled: false,
      intervalSeconds: 21600,
      params: { order: 'viewCount' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_economic_reconcile',
      displayName: '경제지표 보정 수집',
      description: '최근 과거와 미래 구간을 다시 조회해 actual/estimate/previous 변경을 반영합니다.',
      domain: 'calendar',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'economic_calendar',
      enabled: false,
      intervalSeconds: 21600,
      params: { daysBack: 7, daysAhead: 30 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_earnings_reconcile',
      displayName: '실적 캘린더 보정 수집',
      description: '실적 발표 전후 구간을 다시 조회해 일정과 실제 EPS 변경을 반영합니다.',
      domain: 'calendar',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'earnings_calendar',
      enabled: false,
      intervalSeconds: 43200,
      params: { daysBack: 14, daysAhead: 45 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'youtube_economy_reconcile',
      displayName: '경제 유튜브 보정 수집',
      description: '이미 저장된 최근 영상의 제목/설명/조회수/썸네일을 다시 가져옵니다.',
      domain: 'youtube',
      operation: 'reconcile',
      provider: 'youtube',
      handler: 'youtube_economy_reconcile',
      enabled: false,
      intervalSeconds: 43200,
      params: { limit: 80 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_popular',
      displayName: '인기 시세 최신 수집',
      description: '인기 종목의 최신 시세를 Finnhub에서 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_quotes',
      enabled: false,
      intervalSeconds: 1800,
      params: { segment: 'popular', listKey: 'popular_symbols' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_watchlist',
      displayName: '관심종목 시세 최신 수집',
      description: '기본 관심종목의 최신 시세를 Finnhub에서 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_quotes',
      enabled: false,
      intervalSeconds: 1800,
      params: { listKey: 'default_watchlist' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_mcap',
      displayName: '시총 상위 시세 수집',
      description: '시총 상위 후보 종목의 최신 시세를 Finnhub에서 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_quotes_mcap',
      enabled: false,
      intervalSeconds: 1800,
      params: { topN: 20, listKey: 'mcap_universe' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_coins_top',
      displayName: '코인 시총 상위 수집',
      description: 'CoinGecko에서 시총 상위 코인 가격을 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'coingecko',
      handler: 'coin_markets',
      enabled: false,
      intervalSeconds: 1800,
      params: { limit: 30 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_kr_after_hours',
      displayName: '국내주식 정규장 외 참고가',
      description: 'Hyperliquid 해외 파생상품 가격을 USD/KRW로 환산해 국내 관심종목의 정규장 외 참고가로 저장합니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'hyperliquid',
      handler: 'korea_after_hours',
      enabled: true,
      intervalSeconds: 60,
      lockTtlSeconds: 180,
      staleLockSeconds: 180,
      params: {
        dex: 'xyz',
        fallbackUsdKrw: 1400,
        notice: '공식 거래소 시세가 아닌 해외 파생상품 기반 참고가입니다.',
        instruments: [
          {
            symbol: '005930',
            name: '삼성전자',
            displaySymbol: 'Samsung Elec',
            yahooSymbol: '005930.KS',
            candidates: ['SMSN', 'SAMSUNG', '005930', 'SAMS', 'SEC'],
            regularCloseKrw: null,
          },
          {
            symbol: '000660',
            name: 'SK하이닉스',
            displaySymbol: 'SK Hynix',
            yahooSymbol: '000660.KS',
            candidates: ['SKHX', 'SKHYNIX', 'HYNIX', '000660'],
            regularCloseKrw: null,
          },
          {
            symbol: '005380',
            name: '현대차',
            displaySymbol: 'Hyundai Motor',
            yahooSymbol: '005380.KS',
            candidates: ['HYUNDAI', 'HYUNDAIMOTOR', '005380'],
            regularCloseKrw: null,
          },
        ],
      },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'quant_price_series_kr',
      displayName: '국내주식 일봉 시세 적재',
      description: 'Yahoo 일봉 OHLCV를 국내 관심종목별로 적재해 퀀트 팩터 엔진의 기반 데이터로 저장합니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'yahoo',
      handler: 'kr_daily_bars',
      enabled: true,
      intervalSeconds: 21600,
      lockTtlSeconds: 600,
      staleLockSeconds: 600,
      params: {
        range: '1y',
        requestDelayMs: 150,
        instruments: [
          { symbol: '005930', name: '삼성전자', displaySymbol: 'Samsung Elec', yahooSymbol: '005930.KS' },
          { symbol: '000660', name: 'SK하이닉스', displaySymbol: 'SK Hynix', yahooSymbol: '000660.KS' },
          { symbol: '005380', name: '현대차', displaySymbol: 'Hyundai Motor', yahooSymbol: '005380.KS' },
          { symbol: '373220', name: 'LG에너지솔루션', displaySymbol: 'LG Energy', yahooSymbol: '373220.KS' },
          { symbol: '207940', name: '삼성바이오로직스', displaySymbol: 'Samsung Bio', yahooSymbol: '207940.KS' },
          { symbol: '005490', name: 'POSCO홀딩스', displaySymbol: 'POSCO', yahooSymbol: '005490.KS' },
          { symbol: '035420', name: 'NAVER', displaySymbol: 'NAVER', yahooSymbol: '035420.KS' },
          { symbol: '035720', name: '카카오', displaySymbol: 'Kakao', yahooSymbol: '035720.KS' },
          { symbol: '051910', name: 'LG화학', displaySymbol: 'LG Chem', yahooSymbol: '051910.KS' },
          { symbol: '006400', name: '삼성SDI', displaySymbol: 'Samsung SDI', yahooSymbol: '006400.KS' },
          { symbol: '000270', name: '기아', displaySymbol: 'Kia', yahooSymbol: '000270.KS' },
          { symbol: '068270', name: '셀트리온', displaySymbol: 'Celltrion', yahooSymbol: '068270.KS' },
        ],
      },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'insights_market_brief',
      displayName: '시장 인사이트 생성',
      description: '수집된 뉴스·유튜브·시세·캘린더를 묶어 앱 첫 화면과 푸시 후보용 인사이트를 생성합니다.',
      domain: 'insights',
      operation: 'latest',
      provider: 'signal',
      handler: 'market_insights',
      enabled: true,
      intervalSeconds: 1800,
      lockTtlSeconds: 600,
      staleLockSeconds: 600,
      params: {
        windowHours: 24,
        dateMode: 'today',
        timeZone: 'Asia/Seoul',
        maxItems: 8,
        minScore: 20,
        llmProvider: 'auto',
        pushMinScore: 55,
      },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
  ];
}

export function defaultRssSources() {
  return [
    {
      id: 'financial_juice',
      name: 'Financial Juice',
      providerId: 'financial_juice',
      sourceName: 'Financial Juice',
      feedUrl: 'https://www.financialjuice.com/feed.ashx?xy=rss',
      category: 'global',
      enabled: true,
      hidden: false,
      order: 1,
      defaultLimit: 40,
      daysBack: 0,
      includeKeywords: [],
      excludeKeywords: [],
      updatedAt: nowIso(),
    },
    {
      id: 'globenewswire_earnings',
      name: 'GlobeNewswire 실적',
      providerId: 'globenewswire',
      sourceName: 'GlobeNewswire',
      feedUrl:
        'https://www.globenewswire.com/RssFeed/subjectcode/13-Earnings%20Releases%20and%20Operating%20Results/feedTitle/GlobeNewswire%20-%20Earnings%20Releases%20and%20Operating%20Results',
      category: 'earnings',
      enabled: true,
      hidden: false,
      order: 2,
      defaultLimit: 40,
      daysBack: 7,
      includeKeywords: ['earnings', 'results', 'revenue', 'guidance', 'quarter'],
      excludeKeywords: [],
      updatedAt: nowIso(),
    },
    {
      id: 'prnewswire_earnings',
      name: 'PR Newswire 실적',
      providerId: 'prnewswire',
      sourceName: 'PR Newswire',
      feedUrl: 'https://www.prnewswire.com/rss/news-releases-list.rss',
      category: 'earnings',
      enabled: true,
      hidden: false,
      order: 3,
      defaultLimit: 40,
      daysBack: 7,
      includeKeywords: ['earnings', 'results', 'revenue', 'guidance', 'quarter'],
      excludeKeywords: [],
      updatedAt: nowIso(),
    },
  ];
}

export function defaultProviderSettings() {
  return [
    {
      provider: 'finnhub',
      enabled: true,
      apiKey: config.finnhubToken,
      updatedAt: nowIso(),
    },
    {
      provider: 'openai',
      enabled: true,
      apiKey: config.openaiApiKey,
      defaultModel: 'gpt-4o-mini',
      updatedAt: nowIso(),
    },
    {
      provider: 'claude',
      enabled: true,
      apiKey: config.anthropicApiKey,
      defaultModel: 'claude-3-5-haiku-latest',
      updatedAt: nowIso(),
    },
    {
      provider: 'youtube',
      enabled: true,
      apiKey: config.youtubeApiKey,
      updatedAt: nowIso(),
    },
    {
      provider: 'ninjas',
      enabled: true,
      apiKey: config.ninjasKey,
      updatedAt: nowIso(),
    },
    {
      provider: 'coingecko',
      enabled: true,
      apiKey: '',
      updatedAt: nowIso(),
    },
    {
      provider: 'hyperliquid',
      enabled: true,
      apiKey: '',
      updatedAt: nowIso(),
    },
    {
      provider: 'sec',
      enabled: true,
      apiKey: '',
      updatedAt: nowIso(),
    },
    {
      provider: 'rss',
      enabled: true,
      apiKey: '',
      updatedAt: nowIso(),
    },
  ];
}

export function defaultTranslationSettings() {
  return [
    {
      locale: 'ko',
      provider: config.translationProvider,
      enabled: true,
      autoTranslateNews: true,
      updatedAt: nowIso(),
    },
    {
      locale: 'ja',
      provider: config.translationProvider,
      enabled: false,
      autoTranslateNews: false,
      updatedAt: nowIso(),
    },
  ];
}

export function defaultDb() {
  return {
    meta: { createdAt: nowIso(), updatedAt: nowIso(), schemaVersion: 1, rssSourcesCatalogVersion: 1 },
    appSettings: {
      marketQuotesMaxAgeSec: 10,
      youtubeCurationHandles: [...DEFAULT_YOUTUBE_CURATION_HANDLES],
      updatedAt: nowIso(),
    },
    pollingJobs: defaultPollingJobs(),
    pollingJobRuns: [],
    newsItems: [],
    newsTranslations: [],
    calendarEvents: [],
    concallTranscripts: [],
    youtubeVideos: [],
    marketQuotes: [],
    coinMarkets: [],
    priceSeries: [],
    insightItems: [],
    notificationItems: [],
    marketLists: ensureMarketListsShape([], nowIso),
    providerSettings: defaultProviderSettings(),
    translationSettings: defaultTranslationSettings(),
    uiModelPresets: defaultUiModelPresets(),
    newsSources: [],
    rssSources: defaultRssSources(),
    newsSourceSettings: {
      autoEnableNewSources: { global: true, crypto: true },
      aliases: { global: {}, crypto: {} },
    },
  };
}
