import { config } from '../config.mjs';
import { ensureMarketListsShape } from '../marketLists.mjs';
import { nowIso } from './time.mjs';

export function defaultUiModelPresets() {
  return {
    openai: ['gpt-4o-mini'],
    claude: ['claude-3-5-haiku-latest'],
    mock: ['mock-news-v1'],
    updatedAt: nowIso(),
  };
}

export function defaultPollingJobs() {
  return [
    {
      jobKey: 'market_news_global',
      displayName: '글로벌 뉴스 최신 수집',
      description: 'Finnhub 글로벌 시장 뉴스 최신 목록을 가져옵니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 1800,
      params: { category: 'general' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_crypto',
      displayName: '크립토 뉴스 최신 수집',
      description: 'Finnhub 크립토 뉴스 최신 목록을 가져옵니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 1800,
      params: { category: 'crypto' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_global_reconcile',
      displayName: '글로벌 뉴스 보정 수집',
      description: 'Finnhub 글로벌 시장 뉴스를 다시 조회해 수정된 제목/요약/소스 정보를 반영합니다.',
      domain: 'news',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 3600,
      params: { category: 'general' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_crypto_reconcile',
      displayName: '크립토 뉴스 보정 수집',
      description: 'Finnhub 크립토 뉴스를 다시 조회해 수정된 제목/요약/소스 정보를 반영합니다.',
      domain: 'news',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'market_news',
      enabled: false,
      intervalSeconds: 3600,
      params: { category: 'crypto' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_financial_juice',
      displayName: 'Financial Juice (RSS)',
      description: 'Financial Juice 공개 RSS(지연 헤드라인)를 수집해 뉴스 DB에 저장합니다.',
      domain: 'news',
      operation: 'latest',
      provider: 'rss',
      handler: 'financial_juice',
      enabled: false,
      intervalSeconds: 300,
      params: { feedUrl: 'https://www.financialjuice.com/feed.ashx?xy=rss', limit: 40 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_news_financial_juice_reconcile',
      displayName: 'Financial Juice (RSS) 보정',
      description: 'RSS 항목을 다시 읽어 제목·요약·링크 변경을 반영합니다.',
      domain: 'news',
      operation: 'reconcile',
      provider: 'rss',
      handler: 'financial_juice',
      enabled: false,
      intervalSeconds: 3600,
      params: { feedUrl: 'https://www.financialjuice.com/feed.ashx?xy=rss', limit: 60 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_economic',
      displayName: '경제지표 최신 수집',
      description: '오늘 이후 경제지표 일정을 가져옵니다.',
      domain: 'calendar',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'economic_calendar',
      enabled: false,
      intervalSeconds: 1800,
      params: { daysAhead: 14 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_earnings',
      displayName: '실적 캘린더 최신 수집',
      description: '오늘 이후 실적 발표 일정을 가져옵니다.',
      domain: 'calendar',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'earnings_calendar',
      enabled: false,
      intervalSeconds: 21600,
      params: { daysAhead: 30 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'concall_transcripts_recent',
      displayName: '컨콜 트랜스크립트 최신 수집',
      description: '최근 실적 캘린더의 컨콜 트랜스크립트를 API Ninjas에서 가져옵니다.',
      domain: 'concalls',
      operation: 'latest',
      provider: 'ninjas',
      handler: 'earning_transcripts',
      enabled: false,
      intervalSeconds: 21600,
      params: { daysBack: 45, daysAhead: 2, limit: 25, listKey: 'mcap_universe', fallbackLatest: true },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'youtube_economy_latest',
      displayName: '경제 유튜브 최신 수집',
      description: '설정된 경제/시장 채널의 최신 영상을 가져옵니다.',
      domain: 'youtube',
      operation: 'latest',
      provider: 'youtube',
      handler: 'youtube_economy',
      enabled: false,
      intervalSeconds: 1800,
      params: { order: 'date', handles: ['futuresnow', 'LikeUSStock', 't3chfeed', 'unrealtech', 'lucky_tv'] },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_economic_reconcile',
      displayName: '경제지표 보정 수집',
      description: '최근 과거와 미래 구간을 다시 조회해 actual/estimate/previous 변경을 반영합니다.',
      domain: 'calendar',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'economic_calendar',
      enabled: false,
      intervalSeconds: 21600,
      params: { daysBack: 7, daysAhead: 30 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'calendar_earnings_reconcile',
      displayName: '실적 캘린더 보정 수집',
      description: '실적 발표 전후 구간을 다시 조회해 일정과 실제 EPS 변경을 반영합니다.',
      domain: 'calendar',
      operation: 'reconcile',
      provider: 'finnhub',
      handler: 'earnings_calendar',
      enabled: false,
      intervalSeconds: 43200,
      params: { daysBack: 14, daysAhead: 45 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'youtube_economy_reconcile',
      displayName: '경제 유튜브 보정 수집',
      description: '이미 저장된 최근 영상의 제목/설명/조회수/썸네일을 다시 가져옵니다.',
      domain: 'youtube',
      operation: 'reconcile',
      provider: 'youtube',
      handler: 'youtube_economy_reconcile',
      enabled: false,
      intervalSeconds: 43200,
      params: { limit: 80 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_popular',
      displayName: '인기 시세 최신 수집',
      description: '인기 종목의 최신 시세를 Finnhub에서 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_quotes',
      enabled: false,
      intervalSeconds: 1800,
      params: { segment: 'popular', listKey: 'popular_symbols' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_watchlist',
      displayName: '관심종목 시세 최신 수집',
      description: '기본 관심종목의 최신 시세를 Finnhub에서 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_quotes',
      enabled: false,
      intervalSeconds: 1800,
      params: { listKey: 'default_watchlist' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_quotes_mcap',
      displayName: '시총 상위 시세 수집',
      description: '시총 상위 후보 종목의 최신 시세를 Finnhub에서 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'finnhub',
      handler: 'market_quotes_mcap',
      enabled: false,
      intervalSeconds: 1800,
      params: { topN: 20, listKey: 'mcap_universe' },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'market_coins_top',
      displayName: '코인 시총 상위 수집',
      description: 'CoinGecko에서 시총 상위 코인 가격을 가져옵니다.',
      domain: 'market',
      operation: 'latest',
      provider: 'coingecko',
      handler: 'coin_markets',
      enabled: false,
      intervalSeconds: 1800,
      params: { limit: 30 },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
    {
      jobKey: 'insights_market_brief',
      displayName: '시장 인사이트 생성',
      description: '수집된 뉴스·유튜브·시세·캘린더를 묶어 앱 첫 화면과 푸시 후보용 인사이트를 생성합니다.',
      domain: 'insights',
      operation: 'latest',
      provider: 'signal',
      handler: 'market_insights',
      enabled: false,
      intervalSeconds: 1800,
      params: {
        windowHours: 24,
        maxItems: 8,
        minScore: 20,
        llmProvider: 'auto',
        pushMinScore: 55,
      },
      lastRunAt: null,
      nextRunAt: null,
      updatedAt: nowIso(),
    },
  ];
}

export function defaultProviderSettings() {
  return [
    {
      provider: 'finnhub',
      enabled: true,
      apiKey: config.finnhubToken,
      updatedAt: nowIso(),
    },
    {
      provider: 'openai',
      enabled: true,
      apiKey: config.openaiApiKey,
      defaultModel: 'gpt-4o-mini',
      updatedAt: nowIso(),
    },
    {
      provider: 'claude',
      enabled: true,
      apiKey: config.anthropicApiKey,
      defaultModel: 'claude-3-5-haiku-latest',
      updatedAt: nowIso(),
    },
    {
      provider: 'youtube',
      enabled: true,
      apiKey: config.youtubeApiKey,
      updatedAt: nowIso(),
    },
    {
      provider: 'ninjas',
      enabled: true,
      apiKey: config.ninjasKey,
      updatedAt: nowIso(),
    },
    {
      provider: 'coingecko',
      enabled: true,
      apiKey: '',
      updatedAt: nowIso(),
    },
  ];
}

export function defaultTranslationSettings() {
  return [
    {
      locale: 'ko',
      provider: config.translationProvider,
      enabled: true,
      autoTranslateNews: true,
      updatedAt: nowIso(),
    },
    {
      locale: 'ja',
      provider: config.translationProvider,
      enabled: false,
      autoTranslateNews: false,
      updatedAt: nowIso(),
    },
  ];
}

export function defaultDb() {
  return {
    meta: { createdAt: nowIso(), updatedAt: nowIso(), schemaVersion: 1 },
    appSettings: {
      marketQuotesMaxAgeSec: 10,
      updatedAt: nowIso(),
    },
    pollingJobs: defaultPollingJobs(),
    pollingJobRuns: [],
    newsItems: [],
    newsTranslations: [],
    calendarEvents: [],
    concallTranscripts: [],
    youtubeVideos: [],
    marketQuotes: [],
    coinMarkets: [],
    insightItems: [],
    marketLists: ensureMarketListsShape([], nowIso),
    providerSettings: defaultProviderSettings(),
    translationSettings: defaultTranslationSettings(),
    uiModelPresets: defaultUiModelPresets(),
    newsSources: [],
    newsSourceSettings: {
      autoEnableNewSources: { global: true, crypto: true },
      aliases: { global: {}, crypto: {} },
    },
  };
}
