import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/constants/theme';

export function makeAccountStyles(theme: AppTheme, sf: (n: number) => number) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.bg },
    content: { padding: 16, gap: 12 },
    hero: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.card,
      padding: 18,
      gap: 12,
      overflow: 'hidden',
    },
    card: { borderRadius: 14, borderWidth: 1, borderColor: theme.border, backgroundColor: theme.card, padding: 16, gap: 12 },
    profileHeroCard: {
      borderColor: theme.greenBorder,
      backgroundColor: theme.bgElevated,
    },
    heroLogoRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    signalBars: { width: 36, height: 28, flexDirection: 'row', alignItems: 'flex-end', gap: 3 },
    signalBar: { width: 6, borderRadius: 4, backgroundColor: theme.green },
    signalBar1: { height: 10, opacity: 0.45 },
    signalBar2: { height: 16, opacity: 0.65 },
    signalBar3: { height: 22, opacity: 0.82 },
    signalBar4: { height: 28 },
    kicker: { fontSize: sf(11), fontWeight: '900', color: theme.green },
    title: { fontSize: sf(22), lineHeight: sf(28), fontWeight: '900', color: theme.text },
    lead: { fontSize: sf(13), lineHeight: sf(19), color: theme.textMuted },
    errBox: { borderRadius: 14, borderWidth: 1, borderColor: '#FFD6DA', backgroundColor: theme.dangerDim, padding: 12 },
    errText: { color: theme.danger, fontSize: sf(12), lineHeight: sf(18) },
    noticeText: { color: theme.green, fontSize: sf(12), lineHeight: sf(18), fontWeight: '800' },
    accountTabs: {
      minHeight: 44,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.card,
      flexDirection: 'row',
      padding: 4,
      gap: 4,
    },
    accountTab: {
      flex: 1,
      minHeight: 34,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    accountTabActive: { backgroundColor: theme.greenDim, borderWidth: 1, borderColor: theme.greenBorder },
    accountTabText: { color: theme.textMuted, fontSize: sf(12), fontWeight: '900' },
    accountTabTextActive: { color: theme.green },
    sectionTitle: { color: theme.text, fontSize: sf(16), fontWeight: '900' },
    sectionLead: { color: theme.textMuted, fontSize: sf(12), lineHeight: sf(18), marginTop: -4 },
    authCardTitle: { color: theme.text, fontSize: sf(17), fontWeight: '900', textAlign: 'center' },
    authCardLead: { color: theme.textMuted, fontSize: sf(12), lineHeight: sf(18), textAlign: 'center' },
    input: {
      minHeight: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      color: theme.text,
      paddingHorizontal: 12,
      fontSize: sf(14),
    },
    primaryBtn: { minHeight: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.green },
    primaryBtnDisabled: { backgroundColor: theme.bgElevated, borderWidth: 1, borderColor: theme.border },
    primaryText: { color: '#06100B', fontSize: sf(14), fontWeight: '900' },
    primaryTextDisabled: { color: theme.textDim },
    socialBox: { gap: 12 },
    dividerRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 2 },
    dividerLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: theme.border },
    dividerText: { color: theme.textDim, fontSize: sf(11), fontWeight: '800' },
    emailToggle: {
      minHeight: 42,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingHorizontal: 12,
    },
    emailToggleText: { color: theme.green, fontSize: sf(13), fontWeight: '900' },
    authSwitchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingTop: 2 },
    authSwitchText: { color: theme.textMuted, fontSize: sf(12), fontWeight: '700' },
    authSwitchBtn: { color: theme.green, fontSize: sf(13), fontWeight: '900' },
    termsBox: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      padding: 12,
      gap: 10,
    },
    termsAllRow: { alignItems: 'center' },
    termsAllText: { flex: 1, color: theme.text, fontSize: sf(13), lineHeight: sf(18), fontWeight: '900' },
    termsDivider: { height: StyleSheet.hairlineWidth, backgroundColor: theme.border },
    termsItem: { flexDirection: 'row', alignItems: 'center', gap: 6, minWidth: 0 },
    termsRow: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 2 },
    checkBox: {
      width: 20,
      height: 20,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    checkBoxActive: { borderColor: theme.greenBorder, backgroundColor: theme.greenDim },
    checkText: { color: theme.green, fontSize: sf(12), fontWeight: '900' },
    termsText: { flex: 1, minWidth: 0, color: theme.textMuted, fontSize: sf(11), lineHeight: sf(17) },
    termsConfirmedRow: {
      minHeight: 34,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingHorizontal: 10,
      alignSelf: 'stretch',
    },
    termsConfirmedText: { flex: 1, color: theme.green, fontSize: sf(11), fontWeight: '900' },
    termsEditText: { color: theme.green, fontSize: sf(11), fontWeight: '900' },
    requiredBadge: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    requiredBadgeText: { color: theme.green, fontSize: sf(9), lineHeight: sf(12), fontWeight: '900' },
    termsOpenBtn: {
      width: 28,
      height: 28,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
      flexShrink: 0,
    },
    profileRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    avatar: { width: 56, height: 56, borderRadius: 18, backgroundColor: theme.bgElevated },
    avatarFallback: { width: 56, height: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.greenDim, borderWidth: 1, borderColor: theme.greenBorder },
    avatarText: { color: theme.green, fontSize: sf(22), fontWeight: '900' },
    profileText: { flex: 1, minWidth: 0 },
    profileName: { color: theme.text, fontSize: sf(17), fontWeight: '900' },
    profileEmail: { color: theme.textMuted, fontSize: sf(12), marginTop: 3 },
    accountMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    accountMetaPill: {
      minHeight: 30,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
    },
    accountMetaText: { color: theme.green, fontSize: sf(11), fontWeight: '900' },
    statusStack: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      overflow: 'hidden',
    },
    statusRow: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    statusIcon: {
      width: 26,
      height: 26,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    statusLabel: { flex: 1, minWidth: 0, color: theme.textMuted, fontSize: sf(12), fontWeight: '800' },
    statusValue: { maxWidth: '48%', color: theme.text, fontSize: sf(12), fontWeight: '900', textAlign: 'right' },
    quickGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    quickTile: {
      flexBasis: '48%',
      flexGrow: 1,
      minHeight: 104,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      padding: 12,
      gap: 7,
    },
    quickIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    quickTitle: { color: theme.text, fontSize: sf(13), fontWeight: '900' },
    quickDesc: { color: theme.textMuted, fontSize: sf(10), lineHeight: sf(15), fontWeight: '700' },
    activityStack: { gap: 8 },
    activityRow: {
      minHeight: 58,
      borderRadius: 13,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    activityRowPressed: { opacity: 0.78 },
    activityIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    activityText: { flex: 1, minWidth: 0 },
    activityTitle: { color: theme.text, fontSize: sf(13), fontWeight: '900' },
    activityDesc: { color: theme.textMuted, fontSize: sf(11), lineHeight: sf(16), marginTop: 2 },
    mutedText: { color: theme.textMuted, fontSize: sf(12), lineHeight: sf(18), fontWeight: '700' },
    identityStack: { gap: 8 },
    subSection: {
      borderRadius: 13,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      padding: 12,
      gap: 10,
    },
    subSectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    subSectionTitle: { flex: 1, color: theme.text, fontSize: sf(13), fontWeight: '900' },
    subSectionMeta: { color: theme.green, fontSize: sf(11), fontWeight: '900' },
    subSectionLead: { color: theme.textMuted, fontSize: sf(11), lineHeight: sf(16), fontWeight: '700', marginTop: -2 },
    socialLinkStack: { gap: 8, marginTop: 0 },
    linkChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    linkChip: {
      minHeight: 32,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 11,
    },
    linkChipText: { color: theme.green, fontSize: sf(11), fontWeight: '900' },
    socialLinkRow: {
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 8,
    },
    socialLinkText: { flex: 1, color: theme.text, fontSize: sf(13), fontWeight: '800' },
    identityRow: {
      minHeight: 54,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    smallOutlineBtn: {
      minHeight: 28,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    smallOutlineText: { color: theme.textMuted, fontSize: sf(10), fontWeight: '900' },
    secondaryBtn: {
      minHeight: 40,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.greenDim,
    },
    secondaryText: { color: theme.green, fontSize: sf(13), fontWeight: '900' },
    legalActionStack: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      overflow: 'hidden',
      backgroundColor: theme.bgElevated,
    },
    legalActionRow: {
      minHeight: 48,
      paddingHorizontal: 13,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    legalActionTitle: { flex: 1, color: theme.text, fontSize: sf(13), fontWeight: '900' },
    accountFooter: { gap: 10, paddingTop: 4, paddingHorizontal: 4, alignItems: 'center' },
    footerActionRow: { flexDirection: 'row', justifyContent: 'center', gap: 8, flexWrap: 'wrap' },
    footerActionBtn: {
      minHeight: 28,
      minWidth: 70,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      paddingHorizontal: 11,
    },
    footerActionText: { color: theme.textMuted, fontSize: sf(11), fontWeight: '900' },
    withdrawBtn: { borderColor: '#FFD6DA', backgroundColor: theme.dangerDim },
    withdrawText: { color: theme.danger },
    copyrightText: { color: theme.textDim, fontSize: sf(10), fontWeight: '700' },
  });
}
