import { Platform, StyleSheet } from 'react-native';

import { APP_CONTENT_MAX_WIDTH, APP_WIDE_CONTENT_MAX_WIDTH } from '@/constants/responsiveLayout';
import type { AppTheme } from '@/constants/theme';
import type { FeedContentTypography } from '@/services/feedContentWeightPreference';
import {
  SEGMENT_TAB_ACTIVE_TEXT,
  SEGMENT_TAB_BTN_PADDING_V,
  SEGMENT_TAB_BTN_RADIUS,
  SEGMENT_TAB_FONT_SIZE,
  SEGMENT_TAB_FONT_WEIGHT,
  SEGMENT_TAB_GAP,
  SEGMENT_TAB_LINE_HEIGHT,
  SEGMENT_TAB_OUTER_RADIUS,
  SEGMENT_TAB_PADDING,
} from '@/constants/segmentTabBar';

export function makeQuotesStyles(
  theme: AppTheme,
  sf: (n: number) => number,
  ft: FeedContentTypography,
  changeColors: { up: string; down: string },
) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.bg },
    mainColumn: {
      flex: 1,
      minHeight: 0,
      width: '100%',
      maxWidth: APP_CONTENT_MAX_WIDTH,
      alignSelf: 'center',
    },
    mainColumnWide: {
      maxWidth: APP_WIDE_CONTENT_MAX_WIDTH,
      alignSelf: 'stretch',
    },
    detailPanePad: {
      flex: 1,
      paddingTop: 10,
    },
    topFixed: {
      flexShrink: 0,
      zIndex: 2,
      elevation: Platform.OS === 'android' ? 2 : 0,
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 10,
      backgroundColor: theme.bg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    list: { flex: 1, minHeight: 0 },
    listContent: { paddingHorizontal: 16, paddingTop: 0 },
    segment: {
      flexDirection: 'row',
      backgroundColor: theme.bgElevated,
      borderRadius: SEGMENT_TAB_OUTER_RADIUS,
      borderWidth: 1,
      borderColor: theme.border,
      padding: SEGMENT_TAB_PADDING,
      marginBottom: 8,
      gap: SEGMENT_TAB_GAP,
    },
    segBtn: {
      flex: 1,
      paddingVertical: SEGMENT_TAB_BTN_PADDING_V,
      borderRadius: SEGMENT_TAB_BTN_RADIUS,
      alignItems: 'center',
      justifyContent: 'center',
    },
    segBtnCompact: {
      flex: 0.86,
    },
    segmentDivider: {
      width: 1,
      height: 18,
      alignSelf: 'center',
      marginHorizontal: 2,
      borderRadius: 999,
      backgroundColor: theme.border,
    },
    segBtnActive: {
      backgroundColor: theme.green,
    },
    segText: {
      fontSize: sf(SEGMENT_TAB_FONT_SIZE),
      lineHeight: sf(SEGMENT_TAB_LINE_HEIGHT),
      fontWeight: SEGMENT_TAB_FONT_WEIGHT,
      color: theme.textDim,
    },
    segTextActive: {
      color: SEGMENT_TAB_ACTIVE_TEXT,
    },
    updated: { fontSize: sf(11), fontWeight: '600', color: theme.textMuted, marginBottom: 10 },
    addRow: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
      alignItems: 'center',
    },
    addInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      fontSize: sf(14),
      color: theme.text,
      backgroundColor: theme.card,
    },
    addBtn: {
      flexShrink: 0,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderRadius: 8,
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
    },
    addBtnText: { fontSize: sf(13), fontWeight: '800', color: theme.green },
    watchResetBtn: {
      flexShrink: 0,
      paddingHorizontal: 10,
      paddingVertical: 9,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
      justifyContent: 'center',
    },
    watchResetBtnText: { fontSize: sf(13), fontWeight: '700', color: theme.danger },
    errBox: {
      padding: 12,
      borderRadius: 14,
      backgroundColor: theme.dangerDim,
      borderWidth: 1,
      borderColor: '#FFD6DA',
      marginBottom: 12,
    },
    errText: { fontSize: sf(12), color: theme.danger, lineHeight: sf(18) },
    empty: { fontSize: sf(13), color: theme.textMuted, marginTop: 8 },
    cardGrouped: {
      backgroundColor: 'transparent',
      borderWidth: 0,
      borderRadius: 0,
      paddingHorizontal: ft.pad(16),
      paddingVertical: ft.pad(12),
    },
    swipeRowGrouped: {
      marginBottom: 0,
      borderRadius: 0,
      overflow: 'hidden',
    },
    swipeRight: {
      width: 80,
      height: '100%',
    },
    swipeDeleteBtn: {
      flex: 1,
      backgroundColor: '#7A2E2E',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 8,
    },
    swipeDeleteText: {
      color: '#FFFFFF',
      fontSize: sf(15),
      fontWeight: '800',
    },
    cardTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 6,
    },
    priceCol: {
      flexShrink: 1,
      alignItems: 'flex-end',
      minWidth: 104,
      maxWidth: '48%',
    },
    priceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 8,
    },
    symCol: { flex: 1, minWidth: 0, flexShrink: 1 },
    symBlock: { alignSelf: 'flex-start', maxWidth: '100%' },
    symRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'nowrap',
    },
    symPressable: { flexShrink: 0, minWidth: 0 },
    sym: {
      fontSize: ft.ff(16),
      lineHeight: ft.ff(20),
      fontWeight: ft.titleWeight,
      color: theme.text,
      letterSpacing: 0.5,
    },
    symPrev: {
      fontSize: ft.ff(12),
      fontWeight: ft.metaWeight,
      color: theme.textMuted,
      marginTop: 4,
      lineHeight: ft.ff(17),
    },
    symSub: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(16),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
      marginTop: 4,
    },
    price: {
      maxWidth: '100%',
      fontSize: ft.ff(18),
      lineHeight: ft.ff(22),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    na: { fontSize: sf(16), color: theme.textDim },
    removeBtn: { padding: 2 },
    chg: {
      maxWidth: '100%',
      fontSize: ft.ff(13),
      lineHeight: ft.ff(17),
      fontWeight: ft.emphasisWeight,
      marginTop: 4,
      textAlign: 'right',
    },
    chgUp: { color: changeColors.up },
    chgDn: { color: changeColors.down },
    fail: { fontSize: sf(12), color: theme.danger },
    yahooInline: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      flexShrink: 1,
      minWidth: 0,
      marginLeft: 8,
      paddingVertical: 2,
    },
    yahooInlinePressed: { opacity: 0.75 },
    yahooInlineText: {
      flexShrink: 1,
      minWidth: 0,
      fontSize: ft.ff(12),
      lineHeight: ft.ff(16),
      fontWeight: ft.emphasisWeight,
      color: theme.green,
    },
  });
}
