import { StyleSheet } from 'react-native';

import type { AppTheme } from '@/constants/theme';
import type { FeedContentTypography } from '@/services/feedContentWeightPreference';

export function makeHomeStyles(theme: AppTheme, sf: (n: number) => number, ft: FeedContentTypography) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.bg },
    scroll: { flex: 1 },
    content: {
      paddingHorizontal: 20,
      paddingTop: 18,
      gap: 18,
    },
    focusCard: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      backgroundColor: theme.card,
      padding: 18,
      gap: 12,
      shadowColor: '#000000',
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 2,
    },
    focusTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    focusKickerWrap: {
      minHeight: 28,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    focusKicker: {
      fontSize: sf(12),
      lineHeight: sf(17),
      fontWeight: '900',
      color: theme.green,
    },
    focusScoreBadge: {
      minWidth: 40,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgElevated,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 8,
    },
    focusScoreText: {
      fontSize: sf(12),
      lineHeight: sf(17),
      fontWeight: '900',
      color: theme.text,
    },
    focusSymbols: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(18),
      fontWeight: ft.emphasisWeight,
      color: theme.green,
    },
    focusTitle: {
      fontSize: sf(24),
      lineHeight: sf(32),
      fontWeight: '900',
      color: theme.text,
      letterSpacing: 0,
    },
    focusBody: {
      fontSize: ft.ff(14),
      lineHeight: ft.ff(21),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    focusMiniList: {
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.bgElevated,
    },
    focusMiniRow: {
      minHeight: 42,
      paddingHorizontal: 12,
      paddingVertical: 9,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    focusMiniTitle: {
      flex: 1,
      minWidth: 0,
      fontSize: ft.ff(13),
      lineHeight: ft.ff(19),
      fontWeight: ft.emphasisWeight,
      color: theme.text,
    },
    focusMiniScore: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(17),
      fontWeight: ft.titleWeight,
      color: theme.green,
    },
    focusActionRow: {
      flexDirection: 'row',
      gap: 8,
    },
    focusActionPrimary: {
      flex: 1,
      minHeight: 46,
      borderRadius: 14,
      backgroundColor: theme.green,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      paddingHorizontal: 12,
    },
    focusActionSecondary: {
      flex: 1,
      minHeight: 46,
      borderRadius: 14,
      backgroundColor: theme.bgElevated,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    focusActionPrimaryText: {
      fontSize: sf(14),
      lineHeight: sf(20),
      fontWeight: '900',
      color: '#FFFFFF',
    },
    focusActionSecondaryText: {
      fontSize: sf(14),
      lineHeight: sf(20),
      fontWeight: '900',
      color: theme.text,
    },
    pillRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    errorBox: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.danger,
      backgroundColor: theme.dangerDim,
      padding: 14,
    },
    errorText: {
      fontSize: sf(13),
      lineHeight: sf(19.5),
      color: theme.danger,
      fontWeight: '800',
    },
    signalList: {
      borderRadius: 22,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.card,
    },
    primarySignalCard: {
      minHeight: ft.signalRow(118),
      paddingHorizontal: ft.pad(16),
      paddingVertical: ft.pad(16),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
      backgroundColor: theme.greenDim,
    },
    signalRow: {
      minHeight: ft.signalRow(68),
      paddingHorizontal: ft.pad(16),
      paddingVertical: ft.pad(12),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    decisionHead: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ft.pad(12),
    },
    decisionTextCol: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    decisionMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minWidth: 0,
    },
    decisionLevel: {
      flexShrink: 0,
      fontSize: ft.signalBodyFont(10),
      lineHeight: ft.signalBodyFont(14),
      fontWeight: ft.signalMetaWeight,
      color: theme.textDim,
    },
    decisionTitle: {
      fontSize: ft.signalTitleFont(15),
      lineHeight: ft.signalTitleFont(22),
      fontWeight: ft.signalTitleWeight,
      color: theme.text,
    },
    secondaryDecisionTitle: {
      fontSize: ft.signalTitleFont(14),
      lineHeight: ft.signalTitleFont(20),
      fontWeight: ft.signalTitleWeight,
      color: theme.text,
    },
    scoreBadge: {
      minWidth: ft.weight === 'bold' ? 42 : 38,
      height: ft.weight === 'bold' ? 34 : 30,
      borderRadius: ft.weight === 'bold' ? 17 : 15,
      backgroundColor: theme.greenDim,
      borderWidth: 1,
      borderColor: theme.greenBorder,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: ft.pad(8),
    },
    scoreText: {
      fontSize: ft.signalTitleFont(12),
      fontWeight: ft.signalTitleWeight,
      color: theme.green,
    },
    secondaryScoreBadge: {
      minWidth: 34,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.bgElevated,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: ft.pad(7),
    },
    secondaryScoreText: {
      fontSize: ft.signalBodyFont(11),
      fontWeight: ft.signalTitleWeight,
      color: theme.textMuted,
    },
    decisionBody: {
      fontSize: ft.signalBodyFont(12),
      lineHeight: ft.signalBodyFont(18),
      color: theme.textMuted,
      fontWeight: ft.signalBodyWeight,
    },
    symbolLine: {
      flexShrink: 1,
      minWidth: 0,
      fontSize: ft.signalBodyFont(11),
      lineHeight: ft.signalBodyFont(15),
      fontWeight: ft.signalMetaWeight,
      color: theme.green,
    },
    quoteList: {
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
    },
    quantList: {
      borderRadius: 22,
      overflow: 'hidden',
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
    },
    quantRow: {
      minHeight: ft.row(78),
      paddingHorizontal: ft.pad(16),
      paddingVertical: ft.pad(13),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    quantLeft: { flex: 1, minWidth: 0, gap: 5 },
    quantTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minWidth: 0,
    },
    quantSymbol: {
      flexShrink: 0,
      maxWidth: '45%',
      fontSize: ft.ff(15),
      lineHeight: ft.ff(21),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    quantAction: {
      flex: 1,
      minWidth: 0,
      fontSize: ft.ff(11),
      lineHeight: ft.ff(16),
      fontWeight: ft.emphasisWeight,
      color: theme.green,
    },
    quantSummary: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(18),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    quantScoreBox: {
      minWidth: 44,
      alignItems: 'flex-end',
      gap: 1,
    },
    quantScoreLabel: {
      fontSize: ft.ff(10),
      lineHeight: ft.ff(14),
      fontWeight: ft.metaWeight,
      color: theme.textDim,
    },
    quantScoreValue: {
      fontSize: ft.ff(20),
      lineHeight: ft.ff(25),
      fontWeight: ft.titleWeight,
      color: theme.green,
    },
    quoteRow: {
      minHeight: ft.row(72),
      paddingHorizontal: ft.pad(16),
      paddingVertical: ft.pad(13),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    quoteLeft: { flex: 1, minWidth: 0 },
    quoteRight: { alignItems: 'flex-end', flexShrink: 0 },
    quoteSymbolRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minWidth: 0,
    },
    quoteSymbol: {
      fontSize: ft.ff(16),
      lineHeight: ft.ff(24),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    quoteName: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(18),
      fontWeight: ft.bodyWeight,
      color: theme.textMuted,
    },
    quoteReasonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 7,
      marginBottom: 3,
    },
    quoteReasonChip: {
      minHeight: 22,
      paddingHorizontal: 8,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.bgElevated,
      borderWidth: 1,
      borderColor: theme.border,
    },
    quoteReasonChipHot: {
      backgroundColor: theme.greenDim,
      borderColor: theme.greenBorder,
    },
    quoteReasonText: {
      fontSize: ft.ff(10),
      lineHeight: ft.ff(14),
      fontWeight: ft.emphasisWeight,
      color: theme.textMuted,
    },
    quoteReasonTextHot: {
      color: theme.green,
    },
    quoteCompany: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(17),
      fontWeight: ft.bodyWeight,
      color: theme.textDim,
      marginTop: 2,
    },
    quoteYahoo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      flexShrink: 1,
      minWidth: 0,
      paddingVertical: 2,
    },
    quoteYahooPressed: { opacity: 0.75 },
    quoteYahooText: {
      flexShrink: 1,
      minWidth: 0,
      fontSize: ft.ff(11),
      lineHeight: ft.ff(15),
      fontWeight: ft.emphasisWeight,
      color: theme.green,
    },
    quotePrice: {
      fontSize: ft.ff(16),
      lineHeight: ft.ff(24),
      fontWeight: ft.titleWeight,
      color: theme.text,
    },
    quoteChange: {
      fontSize: ft.ff(12),
      lineHeight: ft.ff(18),
      fontWeight: ft.emphasisWeight,
    },
    evidenceList: {
      borderRadius: 22,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.card,
    },
    primaryAction: {
      minHeight: 52,
      borderRadius: 16,
      backgroundColor: theme.green,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
      marginTop: 2,
    },
    primaryActionIcon: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    primaryActionText: {
      fontSize: sf(15),
      lineHeight: sf(22.5),
      fontWeight: '900',
      color: '#FFFFFF',
    },
    pressed: { opacity: 0.82 },
  });
}
